FAQ Edits
uabrc/uabrc.github.io pull request #208
Opened 2022-04-28 21:29 UTC by mdefende

add sections on carriage returns and invalid account errors as well as convert OOD to Open OnDemand

Fixes #128 #188 and #207

2022-04-28 21:31 UTC, mdefende commented
Also fixes #205

2022-05-10 17:20 UTC, wwarriner requested changes

2022-05-10 17:20 UTC, wwarriner commented on docs/help/faq.md
> +To convert a script written in Windows to be compatible on Linux, use the `dos2unix` command. Just give it the name of the script to convert and it should convert it correctly.
Can you show an example of the usage with an example script name? It's simple sure, but not always to folks who aren't aware the systems have different line endings.

2022-05-11 15:32 UTC, mdefende commented
Should be good to go now

2022-05-11 15:36 UTC, bjoyce3 approved these changes

2022-05-11 15:38 UTC, merged