Fix for width typo
uabrc/uabrc.github.io pull request #212
Opened 2022-05-03 19:13 UTC by jgordini

changed from width to max-width in extra.css
Issue #202

2022-05-03 19:17 UTC, jgordini commented
needs an additional fix.

2022-05-03 19:54 UTC, jgordini commented
added max-width for mobile devices.

2022-05-04 21:10 UTC, mdefende requested changes
There are still a few sections of text from merge conflicts that need to be resolved on the security page.

2022-05-04 21:10 UTC, mdefende commented on docs/uab_cloud/security_setup_basic.md
> +<<<<<<< HEAD
Looks like there are still some merge conflict byproducts in this one.

2022-05-04 21:10 UTC, mdefende commented on docs/uab_cloud/security_setup_basic.md
> +<<<<<<< HEAD
Merge conflict byproduct

2022-05-04 21:10 UTC, mdefende commented on docs/uab_cloud/security_setup_basic.md
> +<<<<<<< HEAD
Merge conflict byproduct

2022-05-04 21:10 UTC, mdefende commented on docs/uab_cloud/volume_setup_basic.md
> +<<<<<<< HEAD
Merge conflict byproduct. Looks like it was just the notation that wasn't removed

2022-05-04 21:13 UTC, jgordini commented
Crap. I'll take care of it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: mdefende ***@***.***>
Sent: Wednesday, May 4, 2022 4:10:47 PM
To: uabrc/uabrc.github.io ***@***.***>
Cc: Gordinier, Jeremy ***@***.***>; State change ***@***.***>
Subject: Re: [uabrc/uabrc.github.io] Fix for width typo (PR #212)


@mdefende requested changes on this pull request.

There are still a few sections of text from merge conflicts that need to be resolved on the security page.

________________________________

In docs/uab_cloud/security_setup_basic.md<https://github.com/uabrc/uabrc.github.io/pull/212#discussion_r865387585>:

>      2. Select "SSH Key" in the "Key Type" drop down box.

         ![!Create Key pair dialog. The dialog form is filled out. The Key Pair Name is set to my_key_pair. ><](./images/key_pairs_002.png)

 5. Click "+ Create Key Pair"

+<<<<<<< HEAD


Looks like there are still some merge conflict byproducts in this one.

________________________________

In docs/uab_cloud/security_setup_basic.md<https://github.com/uabrc/uabrc.github.io/pull/212#discussion_r865388032>:

>
         ![!Key Pairs page. The Key Pairs table has one entry labeled my_key_pair. ><](./images/key_pairs_004.png)

 6. To add the private key on your local machine please see "Add key" under [Add a Private Key](./cloud_remote_access.md#add-a-private-key).

+<<<<<<< HEAD


Merge conflict byproduct

________________________________

In docs/uab_cloud/security_setup_basic.md<https://github.com/uabrc/uabrc.github.io/pull/212#discussion_r865388131>:

>
 To generate a key pair, see instructions located at [Generating Key Pairs](./cloud_remote_access.md#generating-key-pairs).

 1. Click "Import Public Key" to open a dialog box.

 2. Fill out the dialog box.

+<<<<<<< HEAD


Merge conflict byproduct

________________________________

In docs/uab_cloud/volume_setup_basic.md<https://github.com/uabrc/uabrc.github.io/pull/212#discussion_r865388546>:

> @@ -62,6 +62,11 @@ To format a volume, you must have created a volume and attached it to an instanc
 2. Scroll down to "Volumes Attached" and make note of the `<mount>` part of `<volume-name> on <mount>` for your attached volume as it will be used in later steps.

     ![!my_instance overview page. The page has been scrolled to the bottom. The mouse is pointing to a label under the Volumes Attached heading. The mouse is pointing to the Attached To label reading my_volume on /dev/vdb. ><](./images/persistent_volumes_000.png)
+<<<<<<< HEAD


Merge conflict byproduct. Looks like it was just the notation that wasn't removed

—
Reply to this email directly, view it on GitHub<https://github.com/uabrc/uabrc.github.io/pull/212#pullrequestreview-962642260>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AWETBNFL7FKVSNKQAVATWOTVILRVPANCNFSM5U7Z72KA>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2022-05-05 14:29 UTC, jgordini commented
Went in and removed the outdated head sections.

2022-05-06 15:37 UTC, mdefende commented on docs/uab_cloud/security_setup_basic.md
> +>>>>>>> ca7117e354653a2a86a7d96fa9926c3abeb9053b
Can you also remove this commit hash?

2022-05-06 15:38 UTC, mdefende commented
There's just one commit hash left in the security setup page. If you could remove that, we can go ahead and merge this.

2022-05-09 14:41 UTC, mdefende approved these changes

2022-05-09 14:41 UTC, mdefende approved these changes

2022-05-09 14:41 UTC, merged