A Tutorial for viewing Box storage
uabrc/uabrc.github.io pull request #663
Opened 2024-01-16 18:29 UTC by iam4tune

# Pull Request

## Overview

Created a tutorial for users to view their Box storage size.

## Proposed Changes

## Related Issues

Fixes #568

2024-01-23 17:42 UTC, wwarriner requested changes

2024-01-23 17:42 UTC, wwarriner commented on docs/data_management/box_storage.md
> +To find information on Box and how to log in to your Box account, please find the details [here](<hhttps://www.uab.edu/it/home/tech-solutions/file-storage/box>).
Angle brackets not needed as part of a text link, and extra `h` in the URL.

2024-01-26 20:43 UTC, wwarriner requested changes
Everything looks good, with the exception of the two comments on:

- `box_storage.md`
- `enterprise_storage.md`

Thanks Fortune!

2024-01-26 20:43 UTC, wwarriner commented on docs/data_management/enterprise_storage.md
Change name to `storage_alternatives.md`

Don't forget to add an entry under "Data Management" in `mkdocs.yml`.

2024-01-26 20:43 UTC, wwarriner commented on docs/data_management/box_storage.md
Remove this file from the branch.

2024-01-26 20:53 UTC, iam4tune reviewed
Addressed comments for this pull request.

2024-02-09 20:52 UTC, wwarriner submitted a review, later dismissed

2024-02-14 18:07 UTC, closed without merging