Blog anac best
uabrc/uabrc.github.io pull request #682
Opened 2024-02-23 19:12 UTC by iam4tune

# Pull Request

This is a pull request for including information on Best Practices for working with Anaconda Environments.

## Overview

## Proposed Changes

## Related Issues

2024-03-08 18:28 UTC, wwarriner requested changes
Overall this looks good! I have a few thoughts I've commented on in the changes. Happy to discuss.

2024-03-08 20:40 UTC, iam4tune commented on docs/workflow_solutions/using_anaconda.md
> +1. Using Conda and Pip Wisely: While using Cheaha, or any other platform prioritise using Conda packages as comprehensive compatibility and dependency checks are done during installation. Such that d
Include a sentence to state, how packages are installed in order from the yml file.

2024-03-08 20:41 UTC, iam4tune commented on docs/workflow_solutions/using_anaconda.md
> +7. Utilize Third-Party Tools: Tools such as conda-lock can help manage dependencies more efficiently by creating lock files that facilitate fast and reproducible environment setups across different o
I would look this up, and create an article for conda-lock.

2024-03-12 17:47 UTC, wwarriner commented on docs/workflow_solutions/using_anaconda.md
> +7. Utilize Third-Party Tools: Tools such as conda-lock can help manage dependencies more efficiently by creating lock files that facilitate fast and reproducible environment setups across different o
Sounds good, make sure to create a new issue for it that you can resolve later, as a reminder.

2024-05-02 19:20 UTC, wwarriner requested changes

2024-05-02 22:18 UTC, wwarriner approved these changes
Looks good!

2024-05-03 19:02 UTC, merged