An Article for Using Compute Nodes Over Login Nodes
uabrc/uabrc.github.io pull request #698
Opened 2024-03-22 15:45 UTC by iam4tune

# Pull Request

An article specifying why Cheaha users should use Compute Nodes as against the Login Node when using the cluster.  Included images and links to other docs resources for using slurm, OOD, and terminal.

## Overview

Improved on the article.

## Related Issues

Fixes #574

2024-04-02 17:18 UTC, wwarriner requested changes

2024-04-02 17:18 UTC, wwarriner commented on docs/cheaha/images/LoginCompNode.png
Please set the two side-by-side. Ensure they both point to `$HOME` or `~` to make things more compact. We can find a way to have the page rendering the comments.

2024-04-19 19:29 UTC, mdefende approved these changes

2024-04-19 19:29 UTC, mdefende commented on docs/cheaha/getting_started.md
> +Ideally, only non-intensive tasks like editing files, compiling programs, or managing job submissions should be performed on the login node. Compute-intensive tasks, large data analyses, and simulati
remove compiling programs

2024-04-19 19:29 UTC, mdefende commented on docs/cheaha/getting_started.md
> +Ideally, only non-intensive tasks like editing files, compiling programs, or managing job submissions should be performed on the login node. Compute-intensive tasks, large data analyses, and simulati
Remove 'As Cheaha stakeholders we should hold ourselves to best practices, and ensure its optimal performance and accessibility.'

2024-04-19 19:30 UTC, merged