Adding notes on the practice of using `module reset`
uabrc/uabrc.github.io pull request #705
Opened 2024-04-02 13:55 UTC by bdu-birhanu

## Overview
Notes on the practice of using `module reset` command at the start of sbatch scripts.

## Proposed Changes
- Adding notes on the practice of `module reset' in [Modules and Applications](https://docs.rc.uab.edu/cheaha/software/modules/) page.
- link to:
    -  [Job submission](https://docs.rc.uab.edu/cheaha/slurm/submitting_jobs/)
    -  [Practical sbatch](https://docs.rc.uab.edu/cheaha/slurm/practical_sbatch/)
    - [GPU](https://docs.rc.uab.edu/cheaha/slurm/gpu/#scheduling-gpus)
    - [OOD](https://docs.rc.uab.edu/cheaha/open_ondemand/ood_layout/) pages.

## Related Issues
Fixes #524

2024-04-19 19:24 UTC, mdefende requested changes
Change py designation in code blocks back to bash where bash is being used

2024-04-19 19:27 UTC, mdefende commented on docs/cheaha/software/modules.md
> +2. Be selective and only load a specific module version that you need for your current workflow.Loading unnecessary modules can lead to conflicts and inefficiencies.
Add space before Loading

2024-04-22 23:53 UTC, bdu-birhanu commented
> Change py designation in code blocks back to bash where bash is being used

Just fixed.

2024-04-22 23:53 UTC, bdu-birhanu commented on docs/cheaha/software/modules.md
> +2. Be selective and only load a specific module version that you need for your current workflow.Loading unnecessary modules can lead to conflicts and inefficiencies.
Fixed

2024-05-02 19:12 UTC, wwarriner approved these changes
Looks good!

Y'all may need to approve the changes or dismiss the review to proceed.

2024-05-03 19:03 UTC, mdefende approved these changes

2024-05-03 19:03 UTC, mdefende approved these changes

2024-05-03 19:03 UTC, merged