Add details on job cards to Interactive Apps page
uabrc/uabrc.github.io pull request #737
Opened 2024-05-28 15:04 UTC by bdu-birhanu

# Pull Request

## Overview
This pull request enhances the  interactive session page by adding job card information and labeling its various features, as well as adding a GUI for each job states.

## Proposed Changes
- Add  images for job card during the queued, started and running states
- Add an image on how to download the job folder as a zip file 
- Label and describe each features of the job card

## Related Issues
Fixes #468 
Related to #473

2024-05-29 15:22 UTC, wwarriner requested changes
Overall looks good. There are a few notes on the new screenshot that has highlight boxes.

2024-05-29 15:22 UTC, wwarriner commented on docs/cheaha/open_ondemand/images/ood_interactive_sessions-II.png
Good start, I like this, and I think it needs a couple of changes to make it shine.

1. Please rename to use consistent `_` or `-` in name, right now they're mixed.
2. Make the red numbers `1`, `2`, etc., larger in the image.
3. Do your best to make the red boxes not overlap the thing you are wanting to highlight.
4. Give the boxes consistent spacing on all sides of what you want to highlight.
5. Separate the numbers and boxes a little more so they don't overlap, it may make the numbers hard to read.

Something like the following. I completely understand it can be hard to line things up.

![2024-05-29T10-19-11](https://github.com/uabrc/uabrc.github.io/assets/6930772/8476e327-c5d5-4775-a382-0ccee8d68789)

2024-05-29 19:44 UTC, bdu-birhanu commented on docs/cheaha/open_ondemand/images/ood_interactive_sessions-II.png
Thanks, I have made updates to the image as you suggested.

2024-05-31 20:08 UTC, wwarriner approved these changes

2024-05-31 20:08 UTC, merged