Change "Cheaha Storage" to "Storage"
uabrc/uabrc.github.io pull request #880
Opened 2024-12-24 02:18 UTC by bdu-birhanu

# Pull Request

## Overview
This pull request changes the heading "Cheaha Storage " under `nav` in the `mkdocs.yml` 

## Proposed Changes
- Changed "Cheaha Storage to "Storage"

## Related Issues
Fixes #874

2025-01-08 20:15 UTC, wwarriner reviewed
I think separating storage from only being associated with "Cheaha" is great, so I'm happy to see this. Looking at it side-by-side with "Storage Alternative" it feels a bit confusing. A naive question would be what is different between storage and storage alternatives that they need to be separate articles?

So, perhaps we should have

"Cheaha Storage" -> "Research Computing Storage Solutions"
"Storage Alternatives" -> "Alternative Storage Solutions"

Thoughts?

2025-01-10 20:40 UTC, wwarriner commented
I missed a detail. Let's undo these changes. Per our discussion, let's get the main "storage.md" page as the index for data management (for now), splitting out the Cheaha-specific sections into their own page. The Cheaha-specific page would be titled "Cheaha Storage (GPFS)" and it would be a sibling of the LTS and Alternative pages

2025-02-05 20:06 UTC, wwarriner requested changes
Great work, I think this will help lay the foundation for improvements down the line.

2025-02-05 20:06 UTC, wwarriner commented on docs/data_management/index.md
> +
For the sake of symmetry and completeness, let's add a subsection "How Do I Request Individual Cheaha (GPFS) Storage?". Then we can answer very simply that it is created automatically as part of the account creation process.

2025-02-05 22:04 UTC, bdu-birhanu commented on mkdocs.yml
> +      - Cheaha Storage: data_management/cheaha_storage.md
Fixed.

2025-02-18 18:09 UTC, wwarriner requested changes
This looks to be in good shape, except one minor comment. Let's focus on other data management issues next: https://github.com/uabrc/uabrc.github.io/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22admin%3A%20data-mgmt%22

2025-02-18 19:44 UTC, bdu-birhanu commented on docs/data_management/cheaha_gpfs_storage.md
> +The Project Directories are larger than home directories and serves as a storage solution accessible to Labs led by a PI and Core facilities led by a director. It is intended for sharing data and cod
Fixed. Thanks.

2025-03-07 19:33 UTC, mdefende approved these changes

2025-03-07 19:34 UTC, merged